#!/usr/bin/env bash

set -euo pipefail

[[ -z "${DEBUG:-""}" ]] || set -x

. lib/expressions.bash 

usage() {
    echo "usage: $0"
    echo
    echo "A simple interactive calculator. Written for fun. Not for actual use"
}

main() {
    local expr

    if [[ "$#" -ne 0 ]]
    then
	fail "$(usage)"
    fi
    
    echo -n "> "
    read -r expr
    while [[ ${expr} != "q" ]] ; do
	exp_eval "$expr"
	echo -n "> "
	read -r expr
    done
}

fail() {
    local message="${1:-Calc Failed}"
    echo "$message" >&2
    exit 1
}

main "$@"

