#!/usr/bin/env bash

set -euo pipefail

# See https://medium.com/@kentbeck_7670/limbo-on-the-cheap-e4cfae840330
# and https://medium.com/@kentbeck_7670/test-commit-revert-870bbd756864

main() {
    if ./test ; then
	if nothing_to_commit ; then return ; fi
	
	git commit -am "${GDS_TASK:-"tests pass"}"
    else
	git reset --hard
    fi
}

nothing_to_commit() {
    git diff-index HEAD --quiet
}

main "${@}"
